$schema: 'http://json.schemastore.org/travis'

language: bash
sudo: false
dist: trusty

services:
  - docker
env:
  global:
    - 'TERRAFORM_VERSION=0.10.7'
    - 'TERRAFORM_DOCKER_IMAGE=hashicorp/terraform:light'
    - 'TFLINT_DOCKER_IMAGE=hadolint/hadolint'
    - 'YAMLLINT_VERSION=1.0.3'
    - 'BRANCH_PARSE=${TRAVIS_BRANCH/\//-}'
    - 'DOCKER_BUILD_HASHS=$TRAVIS_REPO_SLUG:$BRANCH_PARSE-$TRAVIS_COMMIT'
    - 'DOCKER_BUILD_NUMBER=$TRAVIS_REPO_SLUG:$BRANCH_PARSE-$TRAVIS_BUILD_NUMBER'
    - 'DOCKER_BUILD_LATEST=$TRAVIS_REPO_SLUG:$BRANCH_PARSE-latest'
    - 'DOCKER_REPOS_LATEST=$TRAVIS_REPO_SLUG:latest'


cache:
  directories:
  - .terraform

before_install:
  - docker --version
  - docker pull $TERRAFORM_DOCKER_IMAGE
  - docker pull $TFLINT_DOCKER_IMAGE
jobs:
  include:
    - stage: lint and format
      language: bash
      env:
        - TERRAFORM_COMMAND_FTM="fmt -check=true"
        - TERRAFORM_COMMAND_VALIDATE="validate -check-variables=false"
      before_install: true
      install: true
      before_script: true
      after_script: true
      script:
        - docker run -i -t -v $(pwd):/terraform -w /terraform hashicorp/terraform:light init
        - docker run -i -t -v $(pwd):/terraform -w /terraform hashicorp/terraform:light $TERRAFORM_COMMAND_FTM
        - docker run -i -t -v $(pwd):/terraform -w /terraform hashicorp/terraform:light $TERRAFORM_COMMAND_VALIDATE
        - docker run -i -t -v $(pwd):/terraform -w /terraform wata727/tflint --ignore-module="telia-oss/ecs-fargate/aws"

    - stage: lint and format
      language: bash
      env:
        -  TERRAFORM_COMMAND_FMT="fmt -check=true"
        -  TERRAFORM_COMMAND_VALIDATE="validate -check-variables=true"
      before_install: true
      install: true
      before_script: true
      after_script: true
      script:
        - docker run -i -t -v $(pwd):/terraform -w /terraform/examples/default hashicorp/terraform:light init
        - docker run -i -t -v $(pwd):/terraform -w /terraform/examples/default hashicorp/terraform:light $TERRAFORM_COMMAND_FMT
        - docker run -i -t -v $(pwd):/terraform -w /terraform/examples/default hashicorp/terraform:light $TERRAFORM_COMMAND_VALIDATE
        - docker run -i -t -v $(pwd):/terraform -w /terraform/examples/default wata727/tflint --ignore-module="telia-oss/ecs-fargate/aws,telia-oss/loadbalancer/aws,telia-oss/rds-instance/aws"
    - stage: Build and Test
      before_install: true
      install: true
      before_script: true
      after_script: true
      script:
        - make -C ./docker build

    - stage: Push container
      before_install: true
      install: true
      before_script: true
      after_script: true
      script:
        - echo "LOL"
notifications:
  email: false
