version: '3.3'
services:
  grafana:
    image: teliaoss/grafana-aws-env:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/var/lib/grafana
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
          
  sut:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./test.sh"
    depends_on: 
      - grafana